services:
  cli:
    build:
      context: .
      args:
        BUNDLE_GEMFILE_ARG: ${BUNDLE_GEMFILE:-Gemfile}
        BUNDLER_VERSION_ARG: ${BUNDLER_VERSION:-1.17.3}
        RUBY_VERSION: "${RUBY_VERSION:-2.7.8}"
    volumes:
      - type: bind
        source: .
        target: /app
      - type: bind
        source: $HOME/.aptible/tokens.json
        target: /root/.aptible/tokens.json
